### ISSUE TITLE
Make IA predictions with CCL

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/SkySim5000_IA_infusion#1] opened 2021-10-25 09:38 UTC
We want to have a notebook that will generate xi +/- and Cell with CCL for given IA model  (hopefully TATT)

**Comment by jharno** [comment] 2021-11-04 14:38
The new Treecorr measurements are much faster to produce, taking about 1 minute per tomographic bin combination.  One question that remains concerns the II term, which vanishes in the predictions for the cases where the two tomographic bins are disjoint (e.g. bin11 and 12 are fine, but not 13, 14, 15...), whereas a weak signal is recovered in the mocks. Who's correct who's wrong?

**Comment by mishakb** [comment] 2021-11-05 20:37
The II signal should in die as you get further with disjoint bins and certainly when you get to 1-4 1-5.

**Comment by jharno** [comment] 2021-11-09 09:04
OK, so in this case I need to verify that the II signal I pick in the mocks is consistent with noise.

**Comment by dlanzieri** [comment] 2021-11-29 11:43
Hi @jharno, I tried to fix the predictions for xi+,  but I haven't be able to get rid of drop at large angles.
This is how the xi+ predictions look like if I use a theta range=[0.1,500] arcmin:
![pos_cross (1)](https://user-images.githubusercontent.com/72620117/143857718-59ae5b0a-e753-4c9b-9a22-036ea239c1d2.png)
and here the xi-:
![neg_cross (1)](https://user-images.githubusercontent.com/72620117/143857627-681a4244-d55c-4288-8f21-57af4dfb4b2c.png)
Something weird happens for very large scales and for sub-arcmin scales. 
I checked several times the notebook, there doesn't seem to be any mistakes.  
In CCL the only function that requires as input a range of k is `pyccl.nl_pt.power.PTCalculator`, that compute the various components needed to estimate perturbation theory correlations. Here I used as k-range= [10^-5, 10^3].
To compute the angular power spectrum I used a range of ell=[2,3e5], and for xi a range of theta=[0.1,500]. 
I've checked several DESC or CCL example, I've never found a range of theta so wide. 
I've discussed this with Martin Kilbinger, he thinks that it could depend from the fact that  CCL uses fftlog to compute the xi from the Cls, and so it does not compute xi_+- on the sphere, but does a Fourier transform of the C_ell. 
So might not be correct on very large scales.
But this doesn't explain why Nicaea does not see this drop, because it also uses fftlog too.

**Comment by jharno** [comment] 2021-11-29 12:54
Hi @dlanzieri, This is indeed strange, indeed. Maybe worth checking with the CCL developers to see if they can identify the cause?

**Comment by jharno** [comment] 2023-03-22 07:03
Hi @dlanzieri,it's been a while since we've worked on this issue. Were you able to find what caused the dip at extreme angles, and perhaps get rid of it?

**Comment by jharno** [comment] 2024-03-11 11:50
I have been using the public cosmoSIS to make predictions now with TATT, see the DES-Y3 examples. Closing this as no longer needed. Could reopen if needed, let me know.

**Closed as completed by jharno** 2024-03-11 11:50 UTC
